general.import = [
    "~/.config/alacritty/themes/catppuccin-macchiato.toml"
]

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Thin"

[window]
decorations = "None"

[cursor.vi_mode_style]
shape = "Block"

[env]
TERM = "xterm-256color"
